openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /pipeline:
    get:
      summary: Get pipelines
      responses:
        '200':
          description: A list of pipelines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pipeline'
    post:
      summary: Create a pipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pipeline'
      responses:
        '201':
          description: Pipeline created
components:
  schemas:
    Pipeline:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        stages:
          type: array
          items:
            type: string
